resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:564feac01a3c59ad20dd519db4b391bf41de632302fea8979577762f05fac81d
  name: controller
  newName: quay.io/jooholee/nfs-provisioner-operator
