# permissions for end users to edit nfsprovisioners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfsprovisioner-editor-role
rules:
- apiGroups:
  - cache.jhouse.com
  resources:
  - nfsprovisioners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.jhouse.com
  resources:
  - nfsprovisioners/status
  verbs:
  - get
