# permissions for end users to view nfsprovisioners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfsprovisioner-viewer-role
rules:
- apiGroups:
  - cache.jhouse.com
  resources:
  - nfsprovisioners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.jhouse.com
  resources:
  - nfsprovisioners/status
  verbs:
  - get
