apiVersion: cache.jhouse.com/v1alpha1
kind: NFSProvisioner
metadata:
  name: nfsprovisioner-sample
spec:
  nodeSelector: 
    kubernetes.io/hostname: worker-0.bell.tamlab.brq.redhat.com
  hostPathDir: "/home/core/test"

