oc_gets+=("pods")
oc_gets+=("deploymentconfigs")     
oc_gets+=("deployment")
oc_gets+=("replicasets")       
oc_gets+=("replicationcontrollers")     
oc_gets+=("services")      
oc_gets+=("configmap")       
oc_gets+=("events")
oc_gets+=("routes")
oc_gets+=("csv")
oc_gets+=("installplan")
oc_gets+=("subscription")
oc_gets+=("operatorgroup")
oc_gets+=("${CUSTOM_RESOURCE_LIST[@]}")

# collect oc output of OC desc commands
oc_descs=()
oc_descs+=("pods")

# collect yaml output of OC commands
oc_yamls=()
oc_yamls+=("project")
oc_yamls+=("pods")
oc_yamls+=("deploymentconfig")
oc_yamls+=("deployment")
oc_yamls+=("replicasets")
oc_yamls+=("replicationcontrollers") 
oc_yamls+=("configmap")
oc_yamls+=("services")
oc_yamls+=("routes")
oc_yamls+=("csv")
oc_yamls+=("installplan")
oc_yamls+=("subscription")
oc_yamls+=("operatorgroup")
oc_yamls+=("${CUSTOM_RESOURCE_LIST[@]}")