kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    command:  
    - /bin/sh
    - -c
    - 'trap : TERM INT; sleep 15'
    image: quay.io/jitesoft/alpine
    volumeMounts:
      - name: nfs-pvc
        mountPath: "mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-pvc